version: '3.8'

services:
  api:
    container_name: "osteo_api_${NODE_ENV}"
    image: "osteo_api_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
      - PORT:${PORT}
    build:
      context: ./api
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - osteo-network
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    restart: unless-stopped

networks:
  osteo-network: